language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t diegomr/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true diegomr/docker-react npm run test